// Lcd pinout settings
sbit LCD_RS at RB4_bit;
sbit LCD_EN at RB5_bit;
sbit LCD_D7 at RB3_bit;
sbit LCD_D6 at RB2_bit;
sbit LCD_D5 at RB1_bit;
sbit LCD_D4 at RB0_bit;

// Pin direction
sbit LCD_RS_Direction at TRISB4_bit;
sbit LCD_EN_Direction at TRISB5_bit;
sbit LCD_D7_Direction at TRISB3_bit;
sbit LCD_D6_Direction at TRISB2_bit;
sbit LCD_D5_Direction at TRISB1_bit;
sbit LCD_D4_Direction at TRISB0_bit;

char pot1_string [8];// STRING PARA RECEBER O VALOR CONVERTIDO DA LEITURA DO POTENCIÔMETRO 1
char pot2_string [8];// STRING PARA RECEBER O VALOR CONVERTIDO DA LEITURA DO POTENCIÔMETRO 2
//char apagar [] = {' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ',' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '};

unsigned int pot1 = 0;// VARIAVEL PARA ARMAZENAR O VALOR OBTIDO PELO AN0
unsigned int pot2 = 0;// VARIAVEL PARA ARMAZENAR O VALOR OBTIDO PELO AN1


void Lcd_Init();
void Lcd_Cmd(char out_char);
void ADC_Init();


void main() {
  // PCFG3:0 = 1011 para AN3:0
  // PCFG3:0 = 1101 PARA AN1 e AN0
  // TROCAR NO ADCON1
  
  TRISA0_bit = 1;  // CONFIGURA AN0 COMO ENTRADA
  TRISA1_bit = 1;  // CONFIGURA AN1 COMO ENTRADA
  TRISA2_bit = 1;
  ADCON1 = 0b00001011;//AN3:0 = ENTRADA
  ADC_Init();//INICIALIZA MÓDULO ANALGÓGICO
  CMCON = 0b00000111;//DESABILITA COMPARADORES INTERNOS


  
  while(1)//LOOP INFINITO
  {
    pot1 = ADC_Get_Sample(0);//RECEBE O VALOR DE TENSÃO DO POTENCIOMETRO NA PORTA AN0
    pot2 = ADC_Get_Sample(1);//RECEBE O VALOR DE TENSÃO DO POTENCIOMETRO NA PORTA AN1

    IntToStr (pot1,pot1_string);//CONVERTE O VALOR DO TIPO INTEIRO OBTIDO PELO CONVERSOR AD NA PORTA AN0 PARA UMA STRING
    IntToStr (pot2,pot2_string);//CONVERTE O VALOR DO TIPO INTEIRO OBTIDO PELO CONVERSOR AD NA PORTA AN1 PARA UMA STRING

    Ltrim(pot1_string);//REMOVE TODOS OS ESPAÇOS EM BRANCO LOCALIZADOS A ESQUERDA DO PRIMEIRO CHAR DA STRING COM O VALOR DE AN0
    Ltrim(pot2_string);//REMOVE TODOS OS ESPAÇOS EM BRANCO LOCALIZADOS A ESQUERDA DO PRIMEIRO CHAR DA STRING COM O VALOR DE AN1

    Lcd_Cmd(_LCD_CLEAR); // LIMPA A TELA PARA ATUALIZAR OS VALORES

    Lcd_Out(1,1,"S1:");//ESCREVE A MENSAGEM POT1 NA PRIMEIRA LINHA E PRIMEIRA COLUNA DO DISPLAY LCD
    Lcd_Out_Cp(pot1_string);//ESCREVE O VALOR OBTIDO DO CONVERSOR A/D NA POSIÇÃO EM QUE SE ENCONTRA O CURSOR DO DISPLAY

    Lcd_Out(1,9,"S2:");//ESCREVE A MENSAGEM POT2 NA PRIMEIRA LINHA E DECIMA PRIMEIRA COLUNA DO DISPLAY LCD
    Lcd_Out_Cp(pot2_string);//ESCREVE O VALOR OBTIDO DO CONVERSOR A/D NA POSIÇÃO EM QUE SE ENCONTRA O CURSOR DO DISPLAY

    Delay_ms(100);// AGUARDA 0,1 s
  }
}